name: ci

# Controls when the workflow will run
on:

  # Trigger the workflow on all pushes, except on tag creation
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'

  # Trigger the workflow on all pull requests
  pull_request: ~

  # Allow workflow to be dispatched on demand
  workflow_dispatch: ~

jobs:

  # Calls a reusable CI workflow to build & test the current repository.
  #   We skip jobs that will result in duplicate artifacts, since the code does not depend on the compiler.
  ci:
    name: ci
    uses: ecmwf-actions/reusable-workflows/.github/workflows/ci.yml@v1
    with:
      skip_matrix_jobs: |
        clang-12@ubuntu-20.04
        clang-9@ubuntu-18.04
        clang-12@macos-10.15
