name: docs

# Controls when the workflow will run
on:

  # Trigger the workflow on all pushes, except on tag creation
  push:
    branches:
    - '**'
    tags-ignore:
    - '**'

  # Allow workflow to be dispatched on demand
  workflow_dispatch: ~

jobs:
  docs:
    name: docs
    uses: ecmwf-actions/reusable-workflows/.github/workflows/docs.yml@main
    with:
      system_dependencies: doxygen
