name: "Pull Request Labeler File-based"
on:
- pull_request_target

jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - name: Assign labels from file changes
    - uses: actions/labeler@v5
