name: Code Quality checks and Testing

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches:
      - main
  schedule:
    - cron: "9 2 * * 0" # at 9:02 on sunday

jobs:
  quality:
    uses: ecmwf-actions/reusable-workflows/.github/workflows/qa-precommit-run.yml@v2
    with:
      skip-hooks: "no-commit-to-branch"

  checks:
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12"]
    uses: ecmwf-actions/reusable-workflows/.github/workflows/qa-pytest-pyproject.yml@v2
    with:
      python-version: {% raw %}${{ matrix.python-version }}{% endraw %}
