name: Run Release Please
on:
  push:
    branches:
      - main
      - hotfix

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v4
        with:
          # this assumes that you have created a personal access token
          # (PAT) and configured it as a GitHub action secret named
          # `MY_RELEASE_PLEASE_TOKEN` (this secret name is not important).
          token: {% raw %}${{ secrets.RELEASE_PLEASE_TOKEN }}{% endraw %}
          # optional. customize path to .release-please-config.json
          config-file: .release-please-config.json
          # Currently releases are done from main
          target-branch: {% raw %}${{ github.ref_name }}{% endraw %}
