name: Update Workflows
on:
  workflow_dispatch:

jobs:
  update-workflows:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Update Workflows
      uses: ecmwf-actions/reusable-workflows/anemoi-actions-update@v2

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      if: steps.update.outputs.changes_made == 'true'
      with:
        branch: ci/update-workflows
        title: 'Update GitHub Actions Workflows'
        body: 'This PR updates the GitHub Actions workflows to the latest templates.'
        commit-message: 'Update GitHub Actions workflows'
        delete-branch: true
