name: build-package-hpc
description: |
  A Github action to submit CI jobs to the HPC
inputs:
  github_user:
    description: Github user used to clone package repositories.
    required: true
  github_token:
    description: Github token with read access to needed repositories.
    required: true
  troika_user:
    description: User used to submit troika job.
    required: true
  repository:
    description: Repository name in format owner/repo@ref.
    required: true
  build_config:
    description: |
      Path to build configuration yaml. Relative path from the repository root, 
      e.g. `.github/build-config.yml`.
    required: true
  dependencies:
    description: List of build dependencies in format `owner/repo@ref`. Adds to whatever is specified in the build configuration file, if the same owner/repo is present, the ref is overridden.
    required: false
  python_dependencies:
    description: List of python dependencies to build from source in format `owner/repo@ref`
    required: false
  compiler:
    description: Compiler family.
    required: true
    default: ${{ matrix.compiler }}
  compiler_cc:
    description: C compiler.
    required: true
    default: ${{ matrix.compiler_cc }}
  compiler_cxx:
    description: C++ compiler.
    required: true
    default: ${{ matrix.compiler_cxx }}
  compiler_fc:
    description: Fortran compiler.
    required: true
    default: ${{ matrix.compiler_fc }}
  compiler_modules:
    description: List of compilers to be loaded as modules.
    required: false
    default: ${{ matrix.compiler_modules }}
  build_config_key:
    description: Config name in the build config file.
    required: false
    default: ${{ matrix.config }}
  python_version:
    description: Python version.
    required: false
    default: ${{ matrix.python_version }}

runs:
  using: composite
  steps:
    - name: Check upstream build status
      uses: ecmwf-action/reusable-workflows/check-upstream-conclusion@v2
      with:
        deps: |
          ${{ inputs.dependencies }}
          ${{ inputs.python_dependencies }}

    - name: Parse inputs
      id: inputs
      shell: python3 {0}
      run: |
        import os
        repo, ref = "${{ inputs.repository }}".split("@")
        deps = ",".join("""${{ inputs.dependencies }}""".splitlines())
        py_deps = ",".join("""${{ inputs.python_dependencies }}""".splitlines())
        with open(os.getenv("GITHUB_OUTPUT"), "a") as f:
            print("repo", repo, sep="=", file=f)
            print("ref", ref, sep="=", file=f)
            print("deps", deps, sep="=", file=f)
            print("py_deps", py_deps, sep="=", file=f)

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        repository: ${{ steps.inputs.outputs.repo }}
        ref: ${{ steps.inputs.outputs.ref }}
        token: ${{ inputs.github_token }}

    - name: Run build-package-hpc
      shell: bash
      run: |
        cd ~/build-package-hpc
        poetry run python -m build_package_hpc --config=$GITHUB_WORKSPACE/${{ inputs.build_config }} \
        --config-name=${{ inputs.build_config_key }} \
        build --package=${{ inputs.repository }} \
        --dependencies=${{ steps.inputs.outputs.deps }} \
        --github-user=${{ inputs.github_user }} \
        --github-token=${{ inputs.github_token }} \
        --troika-user=${{ inputs.troika_user }} \
        --compiler=${{ inputs.compiler }} \
        --compiler-cc=${{ inputs.compiler_cc }} \
        --compiler-cxx=${{ inputs.compiler_cxx }} \
        --compiler-fc=${{ inputs.compiler_fc }} \
        --compiler-modules=${{ inputs.compiler_modules }} \
        --python=${{ inputs.python_version }} \
        --python-dependencies=${{ steps.inputs.outputs.py_deps }}
