---
name: cd-pypi

on:
  workflow_call:
    inputs:
      testpypi:
        description: Whether to upload to testpypi instead of pypi.
          Requires secrets.PYPI_TEST_API_TOKEN to be defined.
        type: boolean
        required: false
        default: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"


      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools wheel twine build


      - name: Build and publish to pypi
        if: ${{ !inputs.testpypi }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          python -m build
          twine upload dist/*

      - name: Build and publish to testpypi
        if: ${{ inputs.testpypi }}
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TEST_API_TOKEN }}
        run: |
          python -m build
          twine upload --repository testpypi dist/*
