name: Run pytest tests installation from pyproject toml with report

on:
  workflow_call:
    inputs:
      python_version:
        description: The version of Python binary to use.
        required: false
        default: '3.x'
        type: string
      optional_dependencies:
        description: The optional dependencies to install.
        required: false
        default: 'all,tests'
        type: string
      skip_tests:
        description: The pytest marks to pass to `-m` command.
        required: false
        default: ''
        type: string

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ inputs.python_version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install .[${{ inputs.optional_dependencies }}]
          python -m pip install pytest-md pytest-emoji
      - name: Test with pytest
        id: pytest
        run: |
          REPORT=pytest_${{ inputs.python_version }}.md
          echo "report-path=$REPORT" >> $GITHUB_OUTPUT
          pytest -v -m "${{ inputs.skip_tests }}" --emoji --md $REPORT
        shell: bash -el {0}
      - name: Add report to summary
        if: always()
        run: |
          echo "::group::..."
          FINAL_REPORT=pytest_report_${{ inputs.python_version }}.md
          echo "# Test report (python ${{ inputs.python_version }})" > "$FINAL_REPORT"
          echo "<details><summary>Click to expand!</summary>" >> "$FINAL_REPORT"
          report_variable=$(tail -n+2 ${{ steps.pytest.outputs.report-path }})
          echo "$report_variable" >> "$FINAL_REPORT"
          echo "</details>" >> "$FINAL_REPORT"
          cat "$FINAL_REPORT" >> "$GITHUB_STEP_SUMMARY"
          echo "::endgroup::"
          echo
          echo "====================================================================================="
          echo Markdown summaries: "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID"
          echo "====================================================================================="
