name: test

# Controls when the workflow will run
on:
  # Trigger the workflow on all pushes, except on tag creation
  push:
    branches:
      - main
    tags-ignore:
      - "**"

  # Trigger the workflow on all pull requests
  pull_request: ~

  # Allow workflow to be dispatched on demand
  workflow_dispatch: ~

jobs:
  qa:
    name: qa
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install Dependencies
        run: npm ci

      - name: Code QA
        run: npm run lint-no-fix

  # Calls a reusable CI Node workflow to qa & test another repository.
  ci-node:
    name: ci-node
    needs: qa
    uses: ./.github/workflows/ci-node.yml
    with:
      repository: ecmwf-actions/build-package
      ref: main
      notify_teams: true
    secrets:
      incoming_webhook: ${{ secrets.MS_TEAMS_INCOMING_WEBHOOK }}

  # Calls a reusable CI workflow to sync the current with a remote repository.
  #   It will correctly handle addition of any new and removal of existing Git objects.
  sync:
    name: sync
    needs: qa
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/sync.yml
    secrets:
      target_repository: ${{ secrets.BITBUCKET_REPOSITORY }}
      target_username: ${{ secrets.BITBUCKET_USERNAME }}
      target_token: ${{ secrets.BITBUCKET_PAT }}

  # Calls a reusable CI workflow to build & check the documentation in another repository.
  #   It will install required system dependencies and test Read the Docs build process.
  docs:
    name: docs
    needs: qa
    uses: ./.github/workflows/docs.yml
    with:
      system_dependencies: pandoc
      repository: ecmwf/pyodc
      ref: develop
