name: test

# Controls when the workflow will run
on:
  # Trigger the workflow on all pushes, except on tag creation
  push:
    branches:
      - main
    tags-ignore:
      - "**"

  # Trigger the workflow on all pull requests
  pull_request: ~

  # Allow workflow to be dispatched on demand
  workflow_dispatch: ~

jobs:
  qa:
    name: qa
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node_version }}

      - name: Install Dependencies
        run: npm ci

      - name: Code QA
        run: npm run lint-no-fix

  # Calls a reusable CI workflow to build & test another repository.
  ci:
    name: ci
    needs: qa
    uses: ./.github/workflows/ci.yml
    with:
      repository: ecmwf/odc
      ref: develop
      build_package_inputs: |
        repository: ecmwf/odc
        sha: develop
        dependencies: |
          ecmwf/ecbuild
          ecmwf/eckit
        dependency_branch: develop

  # Calls a reusable CI Python workflow to qa & test another repository.
  ci-python:
    name: ci-python
    needs: qa
    uses: ./.github/workflows/ci-python.yml
    with:
      repository: ecmwf/pyodc
      ref: develop
      build_package_inputs: |
        repository: ecmwf/pyodc
        sha: develop
        dependencies: |
          ecmwf/ecbuild
          ecmwf/eckit
          ecmwf/odc
        dependency_branch: develop
        self_build: false

  # Calls a reusable CI Node workflow to qa & test another repository.
  ci-node:
    name: ci-node
    needs: qa
    uses: ./.github/workflows/ci-node.yml
    with:
      repository: ecmwf-actions/build-package
      ref: main

  # Calls a reusable CI workflow to sync the current with a remote repository.
  #   It will correctly handle addition of any new and removal of existing Git objects.
  sync:
    name: sync
    needs: qa
    if: github.ref == 'refs/heads/main'
    uses: ./.github/workflows/sync.yml
    secrets:
      target_repository: ${{ secrets.BITBUCKET_REPOSITORY }}
      target_username: ${{ secrets.BITBUCKET_USERNAME }}
      target_token: ${{ secrets.BITBUCKET_PAT }}

  # Calls a reusable CI workflow to build & check the documentation in another repository.
  #   It will install required system dependencies and test Read the Docs build process.
  docs:
    name: docs
    needs: qa
    uses: ./.github/workflows/docs.yml
    with:
      system_dependencies: pandoc
      repository: ecmwf/pyodc
      ref: develop
